---
- include_tasks: dnf.yml
  when: ansible_distribution == "Fedora" or (ansible_os_family == "RedHat" and ansible_pkg_mgr == "dnf")

- include_tasks: yum.yml
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "yum"

- include_tasks: apt.yml
  when: ansible_os_family == "Debian"

- include_tasks: pacman.yml
  when: ansible_os_family == "Arch Linux"

- include_tasks: zypper.yml
  when: ansible_os_family == "Suse"
