---
- include_tasks: dnf.yml
  when: ansible_distribution == "Fedora" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 8)

- include_tasks: yum.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version < 8

- include_tasks: apt.yml
  when: ansible_os_family == "Debian"
